test_browser.ts

test: fail rather than hang when chromium isn't installed

---

tools/package.js

Also includes various other fixes to make package.js work on windows,
as well as some stylistic clean-ups.

tools: build propel_windows with package.js

---

api.ts
api_test.ts
backend_test.ts
backprop.ts
dl.ts
mnist.ts
nn_example.ts
repl.ts
tensor.ts
tf.ts
types.ts
website.ts
website/docs.json

Renames $ to T and arange to range 

---

README.md
api.ts
api_test.ts
dl.ts
dl/math/backends/backend.ts
dl/math/backends/backend_cpu.ts
dl/math/backends/backend_webgl.ts
dl/math/backends/kernel_registry.ts
dl/math/backends/types/set_diag.ts
dl/math/math.ts
ops.ts
tensor.ts
tf.ts
types.ts

Implements tensor.setDiag and eye

---

api_test.ts
tensor.ts

Make tensors iterable

---

tools/run.js
tools/test.js

It is unnecessarily recompiling files. Using ts-node and parcel are
already sufficient.

Remove tsc build step.

---

.firebaserc
db.ts
firebase.d.ts
firebase.json
firestore.rules
notebook.ts
notebook_test.ts
test.ts
test_browser.ts
test_isomorphic.ts
tools/build_website_impl.ts
tools/package.js
util.ts
website.ts
website/main.scss
website_main.ts

Fixes issue #10 
See it in action here http://propelml.org/notebook/

Firebase to load/save notebook

---

notebook.ts
notebook_test.ts

Also adds Notebook.onReady for better testing.

Fixes Clone button being displayed when not logged in.

---

website/main.scss

Change notebook's index style

---

src/dl/math/backends/backend_cpu.ts
src/dl/math/ndarray_test.ts
src/matmul_bench.ts

On my machine, on the order of 100x speedup.
To try: `PROPEL=dl ts-node matmul_bench.ts`.
I'm not sure where the benchmark should go.

dl: optimize cpu matmul

---

src/api.ts
src/api_test.ts
src/backprop.ts
src/dataset.ts
src/dataset_test.ts
src/dl.ts
src/matplotlib.ts
src/mnist.ts
src/nn_example.ts
src/ops.ts
src/params_test.ts
src/tensor.ts
src/tf.ts
src/types.ts
src/util.ts

This forces scoping to happen, while still being explicit in parameter naming. It's also less characters than params.scope("...").

API improvements

---

website/common.ts

Thanks to Cem Göktuğ Sorgun for pointing this out.
Fixes #301

Add width/height to avatar img

---

website/db.ts
website/main.scss
website/notebook.ts
website/notebook_test.ts

This pull request lets users add titles to notebooks.
- A "title" h1 is added after the notebookBlurb and before the clone button.
- If there is no title, "Untitled Notebook" is displayed in a light grey.
- If the user is logged in, an edit button is displayed.
- Upon clicking on edit, a form is displayed and the user can edit the title. The changes are sent to Firestore.
Addresses #238

notebook title

---

website/db.ts
website/notebook.ts

Running a new notebook returned an error as there was no title on the new notebooks.
Addresses #315

fix title error on new notebook

---

src/matplotlib.ts
src/output_handler.ts
website/notebook.ts

Fixes #329 
see http://localhost:8080/notebook/?nbId=qScloS2bOMEyiCq781RG

Fix imshow (and support RGB, RGBA)

---

src/im.ts
src/matplotlib.ts
src/output_handler.ts

Also, add support for using `imsave` in web : )

Refactor imshow

---

src/backend.ts
src/backend_test.ts
src/conv_test.ts
src/dl.ts
src/npy.ts
src/ops.ts
src/tensor.ts
src/tensor_util.ts
src/tf.ts
src/types.ts

closes (hopefully) https://github.com/propelml/propel/issues/184, addressing the TODO here:  https://github.com/propelml/propel/blob/master/src/types.ts#L35

Rename BasicTensor to Storage

---

src/im.ts
src/matplotlib.ts
src/output_handler.ts

 [Fix #339] post uint8array instead of tensor to imshow

---

.appveyor.yml

This fixes your problem with #354.

ci: ensure symlinks in propel_deps are properly recreated on appveyor

---

website/common.ts
website/docs.ts
website/main.scss
website/theme_light.scss
website/website.ts

CSS updates

---

website/db.ts
website/main.scss
website/nb.ts

website fixes

---

src/api_test.ts
src/dataset.ts
src/dl.ts
src/dl/math/backends/backend.ts
src/dl/math/backends/backend_cpu.ts
src/dl/math/backends/backend_webgl.ts
src/dl/math/backends/webgl/gather_gpu.ts
src/dl/math/backends/webgl/pad_gpu.ts
src/dl/math/math.ts
src/ops.ts
src/tensor.ts
src/tf.ts
src/tf_binding.cc
src/types.ts

Add expandDims, stack, gather, pad

---

src/dataset.ts
src/dataset_test.ts

From @indutny with smoke test added

dataset: implement naive shuffling

---

website/main.scss

website: fix notebook cell sizing on Edge

---

website/sandbox.ts

Fix querySelector (broke safari)

---

src/api_test.ts

@ritch does this patch make the api tests pass for you on gpu?

Fix reduceMean test

---

src/api.ts
src/api_test.ts
src/dataset.ts
src/im.ts
src/layers_test.ts
src/tensor.ts

Change stack and concat API

---

src/util.ts
website/db.ts
website/nb.ts
website/nb_test.ts

Fixes #323.
Also improve MockDB and title editing.
(Part 1 of 2 in the nb cell refactor)

nb: Don't display delete button if only one cell.

---

src/api.ts
src/api_test.ts

Fix range error

---

src/im.ts
src/matplotlib.ts

imshow bug fixes

---

src/experiment.ts

sgd and minimize should return void.

---

src/backend.ts
src/cache.ts
src/cache_test.ts
src/disk_experiment.ts
src/disk_experiment_test.ts
src/npy_test.ts
src/util.ts
src/util_node.ts
tools/package.js

Fixes a bunch of issues related to bundling.

Fix npm package

---

README.md
website/codemirror.scss
website/common.tsx
website/main.scss
website/nb.tsx
website/pages.tsx
website/syntax.scss

and other visual updates
fixes #437 
fixes #434

Add a twitter

---

website/index.tsx
website/pages.tsx

Break PropelIndex out into its own file.

---

src/tf_binding.cc

Added missing break statement
This was preventing me to run `npm install` on my Linux workstation.

Add missing break statement

---

src/cache.ts
src/cache_test.ts

cache: Handle URLs with query strings.

---

src/dataset_test.ts
src/mnist.ts
src/mnist_test.ts

Make mnist image batches 4D.

---

website/nb.tsx

Addresses issue #236, but without added test per comment from @ry: https://github.com/propelml/propel/issues/236#issuecomment-377963926.

For review: Key bindings for alt+enter to run then insert cell below

---

package.json

Remove d3 from deps (6mb)

---

src/tensor.ts

Typo: Symbol.Iterator demo code
