website/docs.html

Rubber stamp will do. After landing this, re-running gendoc should not cause so much churn.

doc: add source links for classes and member properties

---

notebook.ts
test.ts

This makes bare "tsc" work again.

src: export types that are used in signatures of exported functions

---

api_test.ts
dl.ts
tensor.ts

This is a hack to control device placement inside of DL. There are several places where they rely on globally set NDArrayMath - this is incompatible with how we're using it.
For reference, this error manifest itself as as this:
No data found for NDArray with data id 1. Use dl.ENV.math instead of
constructing your own NDArrayMath. If you need to construct your own
math, make sure this array is allocated after the math construction
We expect the hack introduced here to be cleaned up in future patches.

Fixing DL/GPU tests

---

dl/math/backends/backend_webgl.ts
dl/math/backends/backend_webgl_test.ts

The "delayed storage mode" was already on by default, now it's the only
option.
This is in preparation for future texture memory management changes.

dl: always enable lazy upload to gpu, remove flag

---

.travis.yml
notebook.ts
tools/build_website.ts
util.ts
website.ts

Previously nb output was cached in a server-side render, and
used in the browser without re-executing the cell. Now output
is cached server side, but re-executed client side (only if the user has
JS enabled, obviously).
This is to remove the hack where innerHTML of output cells was
pulled during browser-side initial page render. This optimization
is complicating development.
This also re-enables the notebook-cell-updating feature.

Modify notebook output caching behavior.

---

tools/build_website.js
tools/build_website_impl.ts
tools/run.js
tools/test.js
tools/upload_website.js

For unknown reasons ts-node 4.1.0 doesn't report typescript errors like previous versions did. For example the code
```javascript
if (5 === "5") console.log("what");
```
didn't trigger an error with ts-node 4.1.0 but does with 3.3.0. We don't particularly care about ts-node - so downgrading is the easiest fix.
This popped up while reviewing #203. Thanks Parsa.

Enable typeCheck in ts-node by default

---

test_browser.ts

We suspect there was a slow down in testNNExample introduced in
b5be8e75ee8a3e3bf97604ac8b95763e22f3d79f

Bump timeout for test_browser.

---

src/dl/math/ndarray_test.ts
tsconfig.json

These errors were there at time of the fork; no idea why typescript
didn't catch them before.

dl: fix type errors in ndarray_test

---

website/notebook.ts

Imagine this scenario:
A user has a bad internet connection he/she clicks on the clone btn and expects to see sth, but nothing would happen and he/she clicks multiple times.
When he/she connects to the net all requests go one-by-one and that's what actually happened to me when using Notebook for the first time.

Prevent unintentional cloning

---

src/binding.cc

This deals with the ridiculous memory spikes and long GC pauses when
using the tensorflow backend.
Note that there still seem to be memory leaks when running nn_example_main, but only slowly. 
A simple test program doesn't seem to leak:
```
const t1 = api_1.T(new Float32Array(1e6), [1000, 1000]);
const t2 = api_1.T(new Float32Array(1e6), [1000, 1000]);
for (;;) {
const t3 = t1.mul(t2);
}
```

tf binding: tell v8 about the size of tensor handles

---

website/nb_transpiler.ts
website/nb_transpiler_test.ts

This fixes a bug where the following code would produce a weird error:
import * as p from propel;
(await p.dataset("wine").next()).labels;

nb_transpiler: preserve semicolon after import statement

---

src/tensor.ts

Due to `readonly` props only being able to be set in constructors, needed to change visibility to `private`. Then setting the `id` of the argument in `.assign()` to the object's `id`, in order for backprop to work correctly.
This was done to support in-place ops.

Changing id to private and setting inside assign()

---

src/api_test.ts
src/backend.ts
src/backend_test.ts
src/backprop.ts
src/binding_test.ts
src/dataset_test.ts
src/disk_experiment_test.ts
src/dl.ts
src/format.ts
src/im_test.ts
src/matmul_bench.ts
src/matplotlib.ts
src/mnist.ts
src/mnist_test.ts
src/npy_test.ts
src/ops.ts
src/params_test.ts
src/tensor.ts
src/tensor_util.ts
src/tensor_util_test.ts
src/tf.ts
src/util.ts
src/util_test.ts
tools/presubmit.js
tools/test_isomorphic.ts
tools/test_node.ts
tsconfig.json
tsconfig_local.json
website/notebook_test.ts
website/website_main.ts

This is in preparation for landing the sandboxed notebook.
Starting with that there will be two bundles, one that runs inside the sandbox (which contains propel), and one for the website (containing preact).
Since util.ts is used in both, we have to make sure to not pull each other.

Move tensor utilities to tensor_util.ts

---

src/api.ts
src/api_test.ts
src/tf.ts

cc @qti3e 
```
> python
Python 2.7.14 (default, Sep 25 2017, 09:53:22)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.uint8([255, 255, 255]).mean()
255.0
```

tf: reduceMean should always return float32.

---

README.md
tools/build_website_impl.ts
tools/dev_website.js
website/index.html
website/main.scss
website/nb.ts

The deps commit includes some hacks on parcel to fix a bug - I will send upstream soon
https://github.com/propelml/propel_deps/commit/41035369fe03732c3c8eb08cdff617d46dc11caf#diff-5e9e9af54dc82093dc2e5334dfff25c3

Adds ./tools/dev_website for fast incremental builds 

---

website/db.ts
website/nb.ts

Some test data created from #360 is crashing the production most-recent.
This backports the future scheme onto master until the patch is ready to
land.

Provisionally handle future NotebookDoc scheme.

---

.travis.yml

ci: disable OS X builds because of Travis CI downtime/backlog

---

package.json
website/nb_transpiler.ts
website/nb_transpiler_test.ts
website/sandbox.ts

There is one TODO item left: when acorn encounters a parse error it
throws a SyntaxError, which code position isn't mapped to the
untranspiled source code.

notebook: show accurate stack traces in the notebook

---

package.json

Required for building tensorflow-binding, since with lower node version
(< v8.6.0) gives: `error: use of undeclared identifier 'NAPI_AUTO_LENGTH'`.

Set node version to v8.6.0

---

src/experiment.ts

Removes extra 'e' from 'experiment' in comment.

Fix typo in experiment file

---

src/matplotlib.ts
src/output_handler.ts
website/nb.ts
website/sandbox.ts

* Use one output handler per cell, not one per output.
* Make the output handler responsible creating DOM text nodes.
* Rename 'console' RPC call to 'print()'.

notebook: various output handler improvements

---

src/api_test.ts
src/dl.ts
src/ops.ts
src/tensor.ts
src/tf.ts
src/types.ts

and add tensor.size
I will need these APIs to implement NumPy's `array2string` (`tensor.toString()`)
https://github.com/numpy/numpy/blob/3629e3986333ecdf394924e53265e0d1061e928d/numpy/core/arrayprint.py#L1104-L1106

Implement reduceMin

---

src/output_handler.ts
src/types.ts
src/util.ts
website/main.scss
website/nb.ts
website/nb_test.ts
website/sandbox.ts
website/test_internals.ts

* Use byte length, not string length, when computing the number of bytes
loaded so far.
* handle http.get() errors.
* Reduce the number of type assertions.
* Explicitly indicate the end of a download by calling
downloadProgress(job, null, null).

Some changes to how progress bars are handled

---

tools/website_render.js

This fixes the example output of imread, which previously needed
to be executed before seeing the image.
http://127.0.0.1:8080/docs/#imread

website_render: replace canvas with dataURLs

---

src/util.ts
website/db.ts
website/main.scss
website/nb.ts
website/nb_test.ts

No error/warning in `./tools/tslint.js`
This addresses #297

profile pages

---

tools/gendoc.ts
tools/gendoc_test.ts

Params wasn’t showing up as gendoc.ts wasnt visiting interfaces (#469 ).
To show the interfaces in the docs I added `visitClass` in the [`ts.isInterfaceDeclaration` check](https://github.com/propelml/propel/compare/master...dangerdak:params-docs?expand=1#diff-324e575d0900c95fbd2bbfc469054499R188) but to do this I had to change type signatures for `visitClass`, `classElementName` and `visitProp` - not sure if this is a bad way to do things :grimacing:
I also added `ts.isMethodSignature` and `ts.isPropertySignature` checks to the `visitClass` function.
... Maybe there’s some nicer way to organise all this?
This caused some interfaces from `deps/` to show up (eg `Array` and `Promise`) so I filtered out nodes which contain the excludes from tsconfig.json in their declarations file paths. …

Show interfaces in docs

---

src/util.ts

https://ci.appveyor.com/project/piscisaureus/propel/build/master-build1316
`util_formatImageName` test had a random behavior based on system performance.
this patch removes slow regexs.

Optimize util.formatImageName
